function StateCovariances = loadStateCovariances_v2()

    StateCovariances.sigma_position_meters = 100;        % About 2x the max deviation from truth starting position
    StateCovariances.sigma_velocity_meters_per_sec = .1; % About 2x the max deviation from truth starting velocity
    StateCovariances.sigma_drag_coefficient = 0.05; % Obsolete

    StateCovariances.sigma_x_accel_meters_per_sec2 = 3e-7; 
    StateCovariances.sigma_y_accel_meters_per_sec2 = 3e-8; 
    StateCovariances.sigma_z_accel_meters_per_sec2 = 5e-8;

    StateCovariances.P_Covariance_States = diag([StateCovariances.sigma_position_meters^2, ...
                                                StateCovariances.sigma_position_meters^2, ...
                                                StateCovariances.sigma_position_meters^2, ...
                                                StateCovariances.sigma_velocity_meters_per_sec^2, ...
                                                StateCovariances.sigma_velocity_meters_per_sec^2, ...
                                                StateCovariances.sigma_velocity_meters_per_sec^2, ...
                                                StateCovariances.sigma_drag_coefficient^2]);

    StateCovariances.Q_ProcessNoise = diag([StateCovariances.sigma_x_accel_meters_per_sec2 ^ 2, ...
                                            StateCovariances.sigma_y_accel_meters_per_sec2 ^ 2, ...
                                            StateCovariances.sigma_z_accel_meters_per_sec2 ^ 2]);

end