function EOP_interpolated_simplified = interpolate_EOP(UTC_date_time, EOP_Source)

    time_struct = ComputeTimeSystems(UTC_date_time);
    ECI_ECEF_Transform_Data = get_EOP_data(); % Includes table_EOP_IERS, table_EOP_Celestrak, and nut80

    MJD_UTC = time_struct.mjd_UTC_days;

    if (EOP_Source == "IERS")
        EOP_Baseline = ECI_ECEF_Transform_Data.table_EOP_IERS;
    elseif (EOP_Source == "Celestrak")
        EOP_Baseline = ECI_ECEF_Transform_Data.table_EOP_Celestrak;
    else
        error('Invalid EOP source. Please choose either "IERS" or "Celestrak".');
    end

    % We need the following values in our interpolated EOP structure:
    % - MJD_days
    % - x_pole_arcsec
    % - y_pole_arcsec
    % - dPsi_milli_arcsec
    % - dEpsilon_milli_arcsec
    % - UT1_UTC_sec
    % - LOD_millisec

    % Interpolate the EOP values at the given MJD_UTC
    interp_matrix = interp1(EOP_Baseline.MJD_days, ...
                            [EOP_Baseline.x_pole_arcsec, ...
                             EOP_Baseline.y_pole_arcsec, ...
                             EOP_Baseline.dPsi_milli_arcsec, ...
                             EOP_Baseline.dEpsilon_milli_arcsec, ...
                             EOP_Baseline.UT1_minus_UTC_sec, ...
                             EOP_Baseline.LOD_millisec], ...
                            MJD_UTC);

    % Create a struct to hold the interpolated values
    EOP_interpolated_simplified = struct( ... 
        'MJD_days', MJD_UTC, ...
        'x_pole_arcsec', interp_matrix(1), ...
        'y_pole_arcsec', interp_matrix(2), ...
        'dPsi_milli_arcsec', interp_matrix(3), ...
        'dEpsilon_milli_arcsec', interp_matrix(4), ...
        'UT1_UTC_sec', interp_matrix(5), ...
        'LOD_millisec', interp_matrix(6) ...
    );

    % delta_AT_sec is always in the Celestrak table, so we can interpolate it directly from there regardless of the EOP source choice
    EOP_interpolated_simplified.delta_AT_sec = interp1(ECI_ECEF_Transform_Data.table_EOP_Celestrak.MJD_days, ...
                                                        ECI_ECEF_Transform_Data.table_EOP_Celestrak.TAI_minus_UTC_sec, ...
                                                        MJD_UTC);

    EOP_interpolated_simplified.omega_earth_rad_sec = Constants.OMEGA_EARTH_RAD_S * (1 - (EOP_interpolated_simplified.LOD_millisec * Constants.MILLI_TO_NOM / Constants.SEC_IN_SOLAR_DAY));

    EOP_interpolated_simplified.small_d_delta_psi_1980_deg = EOP_interpolated_simplified.dPsi_milli_arcsec * Constants.MILLI_TO_NOM * Constants.ARCSEC_TO_DEG; % Convert from milli-arcseconds to degrees
    EOP_interpolated_simplified.small_d_delta_epsilon_1980_deg = EOP_interpolated_simplified.dEpsilon_milli_arcsec * Constants.MILLI_TO_NOM * Constants.ARCSEC_TO_DEG; % Convert from milli-arcseconds to degrees

end