function H_Matrix = Compute_H_matrix(in1,in2,in3,in4)
%Compute_H_matrix
%    H_Matrix = Compute_H_matrix(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    23-Apr-2026 11:24:03

r_ECI_meters1 = in1(1,:);
r_ECI_meters2 = in1(2,:);
r_ECI_meters3 = in1(3,:);
r_station_ECI_meters1 = in3(1,:);
r_station_ECI_meters2 = in3(2,:);
r_station_ECI_meters3 = in3(3,:);
v_ECI_meters_s1 = in2(1,:);
v_ECI_meters_s2 = in2(2,:);
v_ECI_meters_s3 = in2(3,:);
v_station_ECI_meters1 = in4(1,:);
v_station_ECI_meters2 = in4(2,:);
v_station_ECI_meters3 = in4(3,:);
t2 = -r_station_ECI_meters1;
t3 = -r_station_ECI_meters2;
t4 = -r_station_ECI_meters3;
t5 = -v_station_ECI_meters1;
t6 = -v_station_ECI_meters2;
t7 = -v_station_ECI_meters3;
t8 = r_ECI_meters1+t2;
t9 = r_ECI_meters2+t3;
t10 = r_ECI_meters3+t4;
t11 = t5+v_ECI_meters_s1;
t12 = t6+v_ECI_meters_s2;
t13 = t7+v_ECI_meters_s3;
t14 = abs(t8);
t15 = abs(t9);
t16 = abs(t10);
t17 = sign(t8);
t18 = sign(t9);
t19 = sign(t10);
t23 = t8.*t11;
t24 = t9.*t12;
t25 = t10.*t13;
t20 = t14.^2;
t21 = t15.^2;
t22 = t16.^2;
t29 = t23+t24+t25;
t26 = t20+t21+t22;
t27 = 1.0./sqrt(t26);
t28 = t27.^3;
H_Matrix = reshape([t14.*t17.*t27,t11.*t27-t14.*t17.*t28.*t29,t15.*t18.*t27,t12.*t27-t15.*t18.*t28.*t29,t16.*t19.*t27,t13.*t27-t16.*t19.*t28.*t29,0.0,t8.*t27,0.0,t9.*t27,0.0,t10.*t27],[2,6]);
end
