function da_dCd = calc_da_dCd(in1,in2,C_drag,in4,in5,sat_is_illuminated,in7)
%calc_da_dCd
%    da_dCd = calc_da_dCd(IN1,IN2,C_drag,IN4,IN5,SAT_IS_ILLUMINATED,IN7)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    21-Apr-2026 11:28:02

r_ECI_meters1 = in1(1,:);
r_ECI_meters2 = in1(2,:);
r_ECI_meters3 = in1(3,:);
v_ECI_meters_s1 = in2(1,:);
v_ECI_meters_s2 = in2(2,:);
v_ECI_meters_s3 = in2(3,:);
t2 = abs(r_ECI_meters1);
t3 = abs(r_ECI_meters2);
t4 = abs(r_ECI_meters3);
t5 = abs(v_ECI_meters_s3);
t10 = -v_ECI_meters_s2;
t14 = r_ECI_meters1.*7.292115146706979e-5;
t15 = r_ECI_meters2.*7.292115146706979e-5;
t6 = t2.^2;
t7 = t3.^2;
t8 = t4.^2;
t9 = t5.^2;
t16 = t15+v_ECI_meters_s1;
t20 = t10+t14;
t11 = t6./1.0e+6;
t12 = t7./1.0e+6;
t13 = t8./1.0e+6;
t18 = abs(t16);
t21 = abs(t20);
t17 = t11+t12+t13;
t19 = t18.^2;
t23 = t21.^2;
t22 = sqrt(t17);
t28 = t9+t19+t23;
t24 = t22.*1.127815308965004e-2;
t29 = sqrt(t28);
t25 = -t24;
t26 = t25+7.98283047808091e+1;
t27 = exp(t26);
da_dCd = [t16.*t27.*t29.*(-5.421e-16);t20.*t27.*t29.*5.421e-16;t27.*t29.*v_ECI_meters_s3.*(-5.421e-16)];
end
