function da_dv = calc_da_dv(in1,in2,C_drag,in4,in5,sat_is_illuminated,in7)
%CALC_DA_DV
%    DA_DV = CALC_DA_DV(IN1,IN2,C_drag,IN4,IN5,SAT_IS_ILLUMINATED,IN7)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    30-Apr-2026 22:53:03

r_ECI_meters1 = in1(1,:);
r_ECI_meters2 = in1(2,:);
r_ECI_meters3 = in1(3,:);
v_ECI_meters_s1 = in2(1,:);
v_ECI_meters_s2 = in2(2,:);
v_ECI_meters_s3 = in2(3,:);
t2 = abs(r_ECI_meters1);
t3 = abs(r_ECI_meters2);
t4 = abs(r_ECI_meters3);
t5 = abs(v_ECI_meters_s3);
t6 = sign(v_ECI_meters_s3);
t11 = -v_ECI_meters_s2;
t15 = r_ECI_meters1.*7.292115146706979e-5;
t16 = r_ECI_meters2.*7.292115146706979e-5;
t7 = t2.^2;
t8 = t3.^2;
t9 = t4.^2;
t10 = t5.^2;
t17 = t16+v_ECI_meters_s1;
t22 = t11+t15;
t12 = t7./1.0e+6;
t13 = t8./1.0e+6;
t14 = t9./1.0e+6;
t19 = abs(t17);
t20 = sign(t17);
t23 = abs(t22);
t24 = sign(t22);
t18 = t12+t13+t14;
t21 = t19.^2;
t26 = t23.^2;
t25 = sqrt(t18);
t31 = t10+t21+t26;
t27 = t25.*1.127815308965004e-2;
t32 = sqrt(t31);
t28 = -t27;
t33 = 1.0./t32;
t29 = t28+7.98283047808091e+1;
t30 = exp(t29);
t34 = C_drag.*t30.*t32.*5.421e-16;
t35 = -t34;
mt1 = [t35-C_drag.*t17.*t19.*t20.*t30.*t33.*5.421e-16,C_drag.*t19.*t20.*t22.*t30.*t33.*5.421e-16,C_drag.*t19.*t20.*t30.*t33.*v_ECI_meters_s3.*(-5.421e-16)];
mt2 = [C_drag.*t17.*t23.*t24.*t30.*t33.*5.421e-16,t35-C_drag.*t22.*t23.*t24.*t30.*t33.*5.421e-16,C_drag.*t23.*t24.*t30.*t33.*v_ECI_meters_s3.*5.421e-16];
mt3 = [C_drag.*t5.*t6.*t17.*t30.*t33.*(-5.421e-16),C_drag.*t5.*t6.*t22.*t30.*t33.*5.421e-16,t35-C_drag.*t5.*t6.*t30.*t33.*v_ECI_meters_s3.*5.421e-16];
da_dv = reshape([mt1,mt2,mt3],3,3);
end
